<?xml version="1.0"?>
<robot name="person" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="xyz" value="1.0 0 0" />
    <xacro:property name="person_width_x" value="0.3" />
    <xacro:property name="person_width_y" value="0.5" />
    <xacro:property name="person_height" value="1.5" />

    <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

    <link name="world" />
  <link name="person">
    <visual>
      <geometry>
        <mesh filename="/usr/share/gazebo-11/media/models/stand.dae" scale="0.5 0.5 0.5"/>
      </geometry>
      <origin xyz="0 0 ${person_height/2}" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${person_width_x} ${person_width_y} ${person_height}"/>
      </geometry>
      <origin xyz="0 0 ${person_height/2}" rpy="0 0 0"/>
      <surface>
        <friction>
          <ode>
            <mu>0.01</mu>
            <mu2>0.01</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <xacro:default_inertial mass="70"/>
  </link>

  <joint name="world_to_person" type="prismatic">
    <axis xyz="1 0 0"/>
    <limit lower="-3" upper="2" velocity="100" effort="100"/> 
    <parent link="world"/>
    <child link="person"/>
    <origin xyz="${xyz}" />
  </joint>

</robot>